### ISSUE TITLE
How can i use tun2socks in native android app?

### ISSUE THREAD

**Issue by plus1998** [iMrDJAi/cordova-plugin-tun2socks-udp-associate#1]
From the translation:
I'm sorry I asked you here. I am a beginner in Android development.I want to connect to the socks server through VPN.But I did not find the ideal module.Thank you for your open source plug-in, this project seems to be what I want, but I will not use it in the native app

**Comment by iMrDJAi** [comment]
@plusl894860970 Hello! This plugin is a modified version of [cordova-plugin-tun2socks](https://github.com/UWNetworksLab/cordova-plugin-tun2socks), which is designed to work with cordova. It uses a custom Android build of the original [badvpn tun2socks](https://github.com/ambrop72/badvpn/wiki/Tun2socks) project.
Generally, `tun2socks` can handle your case. You might be looking for something like [outline-go-tun2socks](https://github.com/Jigsaw-Code/outline-go-tun2socks) or [go-tun2socks-build](https://github.com/xxf098/go-tun2socks-build)...  
Alternatively, you can use the pre-built `.so` [binaries](https://github.com/iMrDJAi/cordova-plugin-tun2socks-udp-associate/tree/main/android/libs) from this plugin. Import them into your project then check the code to figure out how to use them.  
I'm not an experienced Android apps developer, I can't really help you with that. Try searching for some tutorials if you get stuck. Good luck!
